// "use client";
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { topics } from "../type/index"
import { getTopics }  from "../api/topics/index"
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nextjs Tutorials",
  description: "Generated By Jaeyoung",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  /** react hooks > client side rendering */
  // const [topics, setTopics] = useState<topics.getList>([] as topics.getList);
  // useEffect(() => {
  //   getTopics().then(async(res) => setTopics(await res.json()))
  // },[])

  /** nextjs > server side rendering */
  const res = await getTopics();
  const topics = await res.json();
  
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((value:topics.getData) => {
            return <li key={value.id}><Link href={`/read/${value.id}`}>{value.title}</Link></li>
          })}
        </ol>
        {children}
        <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
